qri-io/desktop

- app/models/dataset.ts
- app/models/store.ts
- package.json
- yarn.lock
Adds a first-pass of the app's redux state tree.
> feat: add first-pass model for state tree

- app/actions/api.ts
- app/components/Dataset.tsx
- app/components/DatasetList.tsx
- app/components/Onboard.tsx
- app/containers/AppContainer.tsx
- app/containers/MyDatasetsContainer.tsx
- app/containers/OnboardContainer.tsx
- app/models/store.ts
- app/reducers/index.ts
- app/reducers/myDatasets.ts
- app/reducers/workingDataset.ts
- app/routes.tsx
- app/store/api.ts
- app/store/configureStore.development.ts
- app/store/configureStore.production.ts
working on fitting api middleware to our refactored state tree layout.
I'm also realizing that I renamed your component from App to `Onboarding` in the process @ramfox, holler if that's an issue.
> feat(api): initial pass at API middleware

- app/actions/api.ts
- app/components/Onboard.tsx
- app/models/dataset.ts
- app/models/store.ts
- app/store/api.ts
update API actions to return a promise that resolves after the API request has completed
> refactor(ApiActionThunk): ApiActions return a thunk for chaining

- app/actions/api.ts
- app/components/Dataset.tsx
- app/components/DatasetList.tsx
- app/components/DatasetSidebar.tsx
- app/components/SaveForm.tsx
- app/containers/DatasetContainer.tsx
- app/containers/SaveFormContainer.tsx
- app/reducers/myDatasets.ts
- app/scss/_dataset.scss
- app/scss/_saveform.scss
- app/scss/style.scss
- app/store/api.ts
- Adds a commit/save form in the sidebar (for linked datasets only)
- POSTS commit title and message to `/fsi/save` on submit
- Uses `/links` and `/fsilinks` to determine which datasets are linked (and show a folder icon in the datasets list)
> Save button

- app/actions/api.ts
- app/components/CommitDetails.tsx
- app/components/Dataset.tsx
- app/components/DatasetSidebar.tsx
- app/containers/CommitDetailsContainer.tsx
- app/containers/MetadataContainer.tsx
- app/containers/SchemaContainer.tsx
- app/models/store.ts
- app/reducers/commitDetail.ts
- app/reducers/index.ts
- app/scss/_dataset.scss
- Show add and remove in component status items
- Show unused components as disabled/subdued
- Add historic component status
- Show historic schema and meta as json
> Historic status

- app/actions/api.ts
- app/components/App.tsx
- app/components/Body.tsx
- app/components/Dataset.tsx
- app/components/DatasetSidebar.tsx
- app/containers/AppContainer.tsx
- app/models/store.ts
- app/reducers/myDatasets.ts
- app/reducers/ui.ts
- app/store/api.ts
- app/store/configureStore.development.ts
- Refactors api calls to use new features of the backend. Closes #84
- consolidates /list and /fsilinks
- changes /ping to /health
- Restores commented out setInterval to poll fsi dataset status
- Hides polling API calls from redux tools in development mode for developer sanity
> 84 refactor api calls

- app/actions/api.ts
- app/components/App.tsx
- app/components/CommitDetails.tsx
- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/DatasetSidebar.tsx
- app/components/UnlinkedDataset.tsx
- app/components/chrome/HeaderColumnButton.tsx
- app/components/chrome/HeaderColumnButtonDropdown.tsx
- app/components/modals/LinkDataset.tsx
- app/containers/AppContainer.tsx
- app/models/modals.ts
- app/reducers/myDatasets.ts
- app/reducers/selections.ts
- app/reducers/workingDataset.ts
- app/scss/_dataset.scss
- app/scss/_modal.scss
- Activates "link to filesystem" button with modal, error handling, etc (Closes #29)
- Restores status tab with a call to action to link the dataset in the main content area (Closes #116)
- Allows resize of sidebar when dataset list is open (Closes #115)
- Cleanup CSS for the dataset header, things are more nicely aligned
> feat: link to filesystem

- app/main.development.js
- package.json
Recently added menu item functionality broken Windows at startup. Add some options to the installer so that it behaves more like a normal application installer.
> fix(windows): Fix Windows crashes at startup. Improve installer.

- CODE_OF_CONDUCT.md
- CONTRIBUTOR.md
- DEVELOPER.md
- Makefile
- README.md
> docs(readmes): add code of conduct, contributer, developer, changelog and small makefile

- app/reducers/myDatasets.ts
Fixes bug that thinks you have no datasets when you scroll
> fix(myDatasets): don't discard the pageInfo!

- app/actions/api.ts
- app/components/DatasetList.tsx
filter needs to be preserved when we close and reopen the dataset list
closes #174
> fix(DatasetList): fix filter

- app/actions/api.ts
- app/components/App.tsx
- app/components/Dataset.tsx
- app/components/DatasetComponent.tsx
- app/components/chrome/HeaderColumnButtonDropdown.tsx
- app/components/modals/AddDataset.tsx
- app/components/modals/CreateDataset.tsx
- app/reducers/workingDataset.ts
- app/store/api.ts
- app/store/mapError.ts
closes #206  
closes #194
closes #168
> fix(api, init, add, profile menu): More fixes and refactoring

- app/store/api.ts
left in a linting error while merging
> chore(api): linting error

- app/app.production.html
- app/main.development.js
- webpack.config.production.js
On windows, need to add a guard on menu interaction, otherwise the user can't close the app at all. For production, depend on the proper css bundle.
> fix(windows): Fix some things for Windows and production build

- app/actions/api.ts
- app/components/DatasetList.tsx
- app/scss/_dataset-list.scss
- package.json
- Updates `concurrently` which had a dependency vulnerability
- Content, layout, and style improvements to the dataset list (Closes #37)
- Full width filter input with X to clear text
- Moved dataset count and "showing" text to bottom of the sidebar
- Show `peername/name` as the primary text, show `meta.title` if it exists as secondary text
> Dataset list items

- app/actions/api.ts
- app/actions/mappingFuncs.ts
- app/components/App.tsx
- app/components/Body.tsx
- app/components/CommitDetails.tsx
- app/reducers/commitDetail.ts
- app/reducers/myDatasets.ts
- app/reducers/selections.ts
- app/reducers/workingDataset.ts
- test/e2e/e2e.spec.ts
closes #223 
closes #191 
closes #196 
This fixes our loading bugs, however, the app doesn't feel as snappy. Trade off for knowing exactly what is happening when and why and at what time. We can build on this!
> Refactor(*): stabilizing app

- app/actions/mutations.ts
- app/components/CommitDetails.tsx
- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/DatasetList.tsx
- app/components/DatasetSidebar.tsx
- app/components/NoDatasets.tsx
- app/components/SaveForm.tsx
- app/components/WelcomeTemplate.tsx
- app/containers/DatasetContainer.tsx
- app/containers/SaveFormContainer.tsx
- app/reducers/mutations.ts
- app/routes.tsx
- app/scss/_dataset.scss
- app/scss/_welcome.scss
closes #231 
closes #232 
this will fail on circle ci until #233 is merged and this branch is rebased!
> fix(NoDatasets, SaveForm): refactor our 'no datasets' story, fix commit bug

- app/components/DatasetSidebar.tsx
Fixes the bug that was causing the selected commit to not highlight.  Closes #243
> fix: commit highlighting

- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/DatasetList.tsx
- app/components/DatasetSidebar.tsx
- app/components/modals/CreateDataset.tsx
Changes some of the tooltips to have clearer/simpler language.  Closes #110
> refactor: tooltip audit

- app/actions/api.ts
- app/actions/ui.ts
- app/components/App.tsx
- app/components/Body.tsx
- app/components/Dataset.tsx
- app/components/DatasetSidebar.tsx
- app/components/Signin.tsx
- app/components/Signup.tsx
- app/components/chrome/Spinner.tsx
- app/components/chrome/Toast.tsx
- app/containers/AppContainer.tsx
- app/containers/DatasetSidebarContainer.tsx
- app/containers/SaveFormContainer.tsx
- app/models/store.ts
- app/reducers/commitDetail.ts
- app/reducers/connection.ts
- app/reducers/index.ts
- app/reducers/mutations.ts
- app/reducers/myDatasets.ts
- app/reducers/page.ts
- app/reducers/selections.ts
- app/reducers/ui.ts
- app/reducers/workingDataset.ts
- app/scss/_dataset.scss
- app/store/api.ts
- app/utils/actionType.ts
- app/utils/bodyValue.ts
- test/app/reducers/connection.test.ts
- test/app/utils/actionTypes.test.ts
closes #237 
closes #236 
closes #77 
- clears commitDetails, when we go to request a new dataset
- doesn't clear workingDataset, if the dataset fail error is 422. This was causing some flashing. We are about to re-request the dataset with `fsi=false`
> fix(*): fetchWorkingDataset, CommitDetails & WorkingDataset handling body, failed to fetch errors

- app/actions/session.ts
- app/components/App.tsx
- app/components/Body.tsx
- app/components/Dataset.tsx
- app/containers/AppContainer.tsx
- app/main.development.js
- app/package.json
- app/reducers/ui.ts
- app/store/api.ts
closes #261 
closes #260 
closes #189 
closes #250
> fix(bootstrap, backend version, defaultPollInterval, pageInfo): lots of fixes

- app/actions/api.ts
- app/actions/mappingFuncs.ts
- app/reducers/workingDataset.ts
> fix:restore body pagination

- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/DatasetList.tsx
- app/components/DatasetSidebar.tsx
- app/components/SaveForm.tsx
- app/components/modals/AddDataset.tsx
- app/components/modals/CreateDataset.tsx
- app/components/modals/Error.tsx
- app/scss/_dataset.scss
- app/store/mapError.ts
- test/e2e/e2e.spec.ts
- yarn.lock
closes #266 
closes #263 
closes #248
> tests(e2e): expand e2e tests

- app/actions/ui.ts
- app/components/App.tsx
- app/components/DatasetSidebar.tsx
- app/components/modals/ExportVersion.tsx
- app/containers/AppContainer.tsx
- app/main.development.js
- app/models/modals.ts
- app/models/store.ts
- app/reducers/ui.ts
- package.json
- yarn.lock
uses `electron-dl` package to manage downloads
> feat(export): export a specific version of a dataset

- app/components/FormatConfigHistory.tsx
- app/components/modals/Modal.tsx
I had to fix these character case issues to get a local dev copy to run.
> Fix type-sensitive imports

- app/actions/api.ts
> refactor(removeDataset): adjust action to work with new api flags

- app/components/StatsChart.tsx
- package.json
- stories/0-Stats.stories.tsx
- stories/data/stats_all_types.json
- yarn.lock
Also adds a stat overview story
> feat(Boolean Stat Chart): add boolean stat, move Stat component

- app/components/DetailsBar.tsx
- app/components/StatsChart.tsx
some merge bugs when we renamed the `Stat` component `StatsChart`
> fix(StatsChart): fix rename bugs

- app/components/DetailsBar.tsx
- app/scss/_dataset.scss
Adds the `type` of stat into the details bar. also adjusts some css
> refactor(DetailsBar): add stat type

- CHANGELOG.md
- app/package.json
- package.json
- version.js
Welcome to Qri Desktop 0.3.0! We've made a huge overhaul on our UI and UX design in this release as well as streamlined some key flows in the app.
We've changed the layout of our app to switch between two main views: the Collections view and the Dataset view. On the Collections page, you can view a list of all your datasets, get important key details about them, and use drag and drop functionality to create a new dataset from an existing file easily. The Dataset page is where you can view and edit a specific dataset. The 'Status' pane reflects the status of the dataset as it exists now, highlighting changes you have made since your last commit and allowing you to make edits to the structure, metadata, and readme portions of your dataset. The 'History' pane allows you to explore previous …
> chore(*): version bump and release notes

- app/components/compare/LineDiff.tsx
- app/components/compare/TableDiff.tsx
- app/scss/_lineDiff.scss
- app/scss/_tableDiff.scss
- app/scss/style.scss
- stories/2-LineDiff.stories.tsx
- stories/3-TableDiff.stories.tsx
Initial UI experiments working out format for displaying diffs, and an accompanying data format
> initial line & table diff components

- CHANGELOG.md
- app/package.json
- package.json
- version.js
This release brings a two new features and some fixes that address bugs that occured while navigating through the app.
You can now edit a schema straight from the app! You can change the title, type, and description of your columns by using our new Schema Editor. Validation is also included in this Schema Editor, but future refinements will be made to get it to be more functional.
If you are having a problem with the app and you want to file an issue, you can now get a copy of your app's debug log by navigating to `help` -> `Export debug log`. This will give the developers more insight into what may have gone wrong.
There were a whole slew of bugs that arose when we switched the way we route the app. This release fixes those bugs and brings back a smooth user experience. Also, additional …
> chore(release): version bump v0.3.2

- CHANGELOG.md
- app/package.json
- package.json
- version.js
Quick patch release to address some bugs when viewing the body!
> chore(release): version bump to 0.3.3

- app/components/Collection.tsx
- app/components/CommitDetails.tsx
- app/components/Layout.tsx
- app/components/chrome/Breadcrumb.tsx
- app/components/nav/Navbar.tsx
- app/components/network/Network.tsx
- app/components/workbench/Workbench.tsx
- app/scss/0.4.0/network.scss
> refactor(Layout): rename `SidebarLayout` to `Layout` & add `NavbarContainer`

- app/components/chrome/ActionButton.tsx
- app/components/chrome/ActionButtonBar.tsx
- app/components/chrome/Hamburger.tsx
- app/components/dataset/CommitPreview.tsx
- app/components/dataset/Dataset.tsx
- app/components/dataset/Overview.tsx
- app/components/dataset/Preview.tsx
- app/components/dataset/TitleBar.tsx
- app/components/modals/SearchModal.tsx
- app/components/network/Network.tsx
- app/components/network/NetworkHome.tsx
- app/components/overlay/HamburgerOverlay.tsx
- app/containers/NetworkContainer.tsx
- app/models/dataset.ts
- app/routes.tsx
- app/scss/0.4.0/network.scss
- app/store/api.ts
you can now open the network tab and click the dataset to be taken to the dataset preview!
> feat (network preview & home)

- app/actions/api.ts
- app/actions/mappingFuncs.ts
- app/components/DatasetList.tsx
- app/components/item/VersionInfoItem.tsx
- app/components/network/Network.tsx
- app/components/network/NetworkHome.tsx
- app/containers/NetworkContainer.tsx
- app/models/qriRef.ts
- app/models/store.ts
- app/routes.tsx
- tsconfig.dev.json
- tsconfig.json
- version.js
We've been working on the refString -> QriRef -> VersionInfo -> Dataset chain of data enrichment.
This commit is a first-cut to introduce two data models we intend to rely on heavily as we tie more things back to the router
> feat(QriRef): rename DetailedDatasetRef to VersionInfo, introduce QriRef

- app/scss/0.4.0/network.scss
Prevents a long list from overflowing the modal.
> style: fix search modal overflow bug

- app/components/Navbar.tsx
- app/components/chrome/Icon.tsx
- app/components/compare/Compare.tsx
- app/components/compare/CompareSidebar.tsx
- app/components/compare/DiffStat.tsx
- app/components/compare/LineDiff.tsx
- app/components/compare/TableDiff.tsx
- app/components/compare/TableDiffSchemaHead.tsx
- app/components/form/ButtonInput.tsx
- app/routes.tsx
- app/scss/0.4.0/compare.scss
- app/scss/0.4.0/icons.scss
- app/scss/_sidebar-layout.scss
- app/scss/_tableDiff.scss
- app/scss/style.scss
- webpack.config.development.js
- webpack.config.production.js
builds on #469. I'll rebase after it's merged
Things to check & fix:
> feat(compare): compare two csv files with compare section

- app/components/StatsChart.tsx
- app/components/chrome/Icon.tsx
- app/components/workbench/Body.tsx
- app/components/workbench/MetadataEditor.tsx
closes #467 
- Commit Icon
- StatsChart weird scrolling issue
- MetadataEditor tooltips
- fixes error in `Body` that was no correctly passing data to the `BodyJson` component
> fix(*) punchlist

- app/components/Layout.tsx
- app/components/workbench/CommitDetails.tsx
- app/components/workbench/CommitDetailsHeader.tsx
- app/scss/_dataset.scss
we go to all this effort for immutability, we should show it!
> feat(history): show hash in CommitDetailsHeader

- README.md
Addresses https://github.com/qri-io/desktop/issues/489
> docs(testing): added input on how to set up and run tests

- .circleci/config.yml
- app/actions/api.ts
- app/components/chrome/ActionButtonBar.tsx
- app/components/item/MetadataMultiInputItem.tsx
closes #511
also changes circleci config to pull backend from master, rather than the latest release
waiting for https://github.com/qri-io/qri/pull/1228 to merge!
> refactor(actions): remove fsi flag

- app/components/workbench/WorkbenchLogList.tsx
> fix(export): send correct path for export

- app/actions/api.ts
- app/components/network/LogList.tsx
- app/package.json
- package.json
- test/e2e/e2e.spec.ts
- version.js
> refactor(api): adjust fetch history calls to match changes in qri backend api

- app/components/onboard/Welcome.tsx
- app/constants.js
> fix: set correct link to github org on welcome screen

- DEVELOPER.md
- app/components/compare/DiffStat.tsx
- app/components/compare/LineDiff.tsx
- app/components/compare/TableDiff.tsx
- app/components/modals/SearchModal.tsx
- app/components/nav/Navbar.tsx
- app/components/network/NetworkHome.tsx
- stories/10-Dataset.stories.tsx
- stories/4-Navbar.stories.tsx
- stories/6-TableDiff.stories.tsx
- stories/Modals.stories.tsx
- stories/Network.stories.tsx
closes #564 
- Refactors stories which rely on an outdated API
- Utilizes "uncontainerized" versions of components to prevent React Router & Redux errors
> fix(Storybook): get all Storybook stories to render

- app/components/form/DynamicEditField.tsx
- app/components/network/LogList.tsx
- app/components/workbench/components/CommitEditor.tsx
- app/components/workbench/components/MetadataEditor.tsx
- app/components/workbench/headerButtons/PublishButton.tsx
- app/components/workbench/layouts/WorkbenchSidebar.tsx
- app/main.development.js
- app/package.json
- app/scss/0.4.0/dataset.scss
- app/scss/0.4.0/network.scss
- app/scss/_dataset.scss
- app/scss/commit.scss
- app/utils/formValidation.ts
- package.json
- test/app/utils/formValidation.test.ts
- version.js
- yarn.lock
closes #597 
closes #596 
closes #595 
closes #552 
closes #591 
closes #592
#593, not able to reproduce the error found by a beta user on windows. Asked for some help from @dustmop or @b5 to see if it is a windows only bug
Going to push #593 to a future pr, if we can repro it
> fix(*): Fix various bugs

- app/components/collection/EditDataset.tsx
- app/components/collection/LogList.tsx
- app/components/collection/layouts/DatasetLayout.tsx
- app/components/collection/layouts/DatasetSidebar.tsx
- app/components/item/HeadLogListItem.tsx
- app/components/item/LogListItem.tsx
- app/components/nav/NavTopbar.tsx
- app/reducers/dataset.ts
- app/scss/0.4.0/network.scss
- app/scss/_dataset.scss
- app/scss/_variables.scss
- app/scss/commit.scss
- stories/11-LogList.stories.tsx
- stories/4-Navbar.stories.tsx
remove "status" and "history" tabs
closes #606 
This does not fix the e2e tests
> feat(`HeadLogListItem`): add history track to sidebar

- app/components/collection/LogList.tsx
- app/main.development.js
Closes #538 
Making this a draft now pending changes we make to the export process. After fixing the export URL I can't reproduce the original error, so planning to just close out that ticket with this refactor since they're related but the orig problem is no longer an issue
> refactor(export dataset): move export config logic to ipcMain handler

- app/components/collection/layouts/DatasetLayout.tsx
- app/components/nav/NavTopbar.tsx
I'd prefer to see these two buttons refactored, but this is the faster way to get them back
> fix(dataset): add back publish & show files buttons

- app/actions/transfers.ts
- app/components/Transfers.tsx
- app/models/store.ts
- app/reducers/transfers.ts
- app/scss/_transfers.scss
- app/store/wsMiddleware.ts
- stories/11-LogList.stories.tsx
- stories/Modals.stories.tsx
- stories/data/remoteEvents.json
- test/app/reducers/transfers.test.ts
* completed transfers also link to their respective dataset.
* moved transfer & websocket event constants into the right places
* updated the transfers Storybook, and a few quick fixes to keep storybook operating
* updated tests
> feat(Transfers): persist transfers after completion

- app/components/DatasetReference.tsx
- app/components/collection/Collection.tsx
- app/components/collection/collectionHome/DatasetList.tsx
- app/components/collection/headerButtons/RenameButton.tsx
- app/components/collection/layouts/DatasetLayout.tsx
- app/components/collection/layouts/DatasetSidebar.tsx
- app/components/modals/Error.tsx
- app/components/modals/Modals.tsx
- app/components/modals/RenameDataset.tsx
- app/models/modals.ts
- app/reducers/platformSpecific/workingDataset.electron.ts
- app/reducers/workingDataset.ts
- app/scss/_dataset.scss
- app/scss/_dialog.scss
- app/utils/formValidation.ts
- stories/10-Dataset.stories.tsx
- stories/11-LogList.stories.tsx
- stories/Modals.stories.tsx
- test/e2e/e2e.spec.ts
- test/e2e/e2e_test_flows.md
- test/utils/e2eTestUtils.ts
closes #637 
Still todo: e2e test fixes
plz read commits for thought process!
> feat(RenameDataset): add `RenameDataset` modal and rename dataset button to dataset page

- app/components/form/SelectInput.tsx
- app/components/form/TextInput.tsx
Removes fixed height for input description text (prevents scrollbar in modals)
> fix: remove fixed height on input descriptions

- app/components/collection/collectionHome/DatasetList.tsx
- app/components/collection/collectionHome/DatasetsTable.tsx
> fix(DatasetList): fix of Collection selected table state
