qri-io/desktop

- app/actions/api.ts
- app/components/CommitDetails.tsx
- app/components/Dataset.tsx
- app/components/DatasetList.tsx
- app/components/DatasetSidebar.tsx
- app/components/Metadata.tsx
- app/containers/CommitDetailsContainer.tsx
- app/containers/DatasetContainer.tsx
- app/containers/MetadataContainer.tsx
- app/models/dataset.ts
- app/models/store.ts
- app/reducers/initalState.ts
- app/reducers/workingDataset.ts
- app/scss/_dataset.scss
This PR includes more progress on wiring up app state:
- Fetches history after working dataset, populates history pane
- Adds a `CommitDetails` component (placeholder)
- Polls for status, reflects working directory files modified/unmodified status with an orange/green dot
- Adds a `Metadata` component, ready to display metadata in the main content area
> Api history and status

- app/components/App.tsx
- app/index.tsx
- app/reducers/selections.ts
- Moves `DatasetContainer` to App, where it is conditionally rendered if `hasDatasets` is true.  This means we aren't rendering it until after the call to `/list` is successful and there are datasets.
- Updates `selections` reducer to set the first dataset returned from `/list` as the selected dataset if there is none already selected.
- Removes `Router` from `index.tsx`, as we are not using routing at all for now (routing was removed in 77782e92f181cc194b5847fbb7cb63fd364fd66b).  `app/routes.tsx` remains in place for whenever we turn routing back on.
Closes #45
> fix: set default working dataset if none selected

- app/actions/api.ts
- app/components/CommitDetails.tsx
- app/components/ComponentList.tsx
- app/components/DatasetSidebar.tsx
- app/models/store.ts
- app/scss/_dataset.scss
- Adds `ComponentList` component, used to render both component status and commit status, deduplicates code in `DatasetSidebar` and `CommitDetails` components.
- Ensures that subtext in component list items (path to file) only shows up for active components on linked datasets (Closes #59 )
- Adds a header to the component list (Closes #53 )
- Refactors commit status api map function so list items are accurate
Edit: appears to have closed #55
> feat: add ComponentList component, ensure correct status behavior

- app/actions/api.ts
- app/actions/session.ts
- app/actions/ui.ts
- app/components/App.tsx
- app/components/ChoosePeername.tsx
- app/components/Onboard.tsx
- app/components/Welcome.tsx
- app/components/WelcomeTemplate.tsx
- app/components/modals/AddDataset.tsx
- app/components/modals/CreateDataset.tsx
- app/containers/AppContainer.tsx
- app/models/session.ts
- app/reducers/index.ts
- app/scss/_dialog.scss
- app/scss/_transitions.scss
- app/scss/_type.scss
- app/store/api.ts
closes #41 - bug in TOS page, (change link from `frontend` to `desktop`)  
closes #42 - wire up ChoosePeername page
This is closed, however this won't be functioning until qri-io/qri#849 
closes #48 - removed 'By Url' tab in AddDataset and add more info and error handling describing what a good dataset reference is
closes #50 - fix CreateDataset submit bug & commented out 'Use existing datafile' tab
This ended up being an error in how we were setting `params` in the api. Fixed now.
> fix(*): Welcome, ChoosePeername, AddDataset, CreateDataset

- app/actions/api.ts
- app/components/App.tsx
- Before firing `fetchWorkingDataset`, check whether the selected dataset `isLinked`.  If it is, add `fsi=true` to the query so it will return the correct data for `meta` and `schema`
Unrelated, this PR also includes a change to call ping the API immediately, then call it again many times with setInterval.  It was waiting to make the first call, which shows the user a loading screen unnecessarily.
> 88 fsi working dataset

- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/DatasetSidebar.tsx
- package.json
- yarn.lock
Adds `react-tooltip`.  
ReactTooltip the component is added at the bottom of the render function in `Dataset.tsx`.  Tooltips can quickly be added by adding a `data-tip={'tooltip text'}` attribute to any element.
Closes #54
> feat: implement tooltips in dataset component

- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/DatasetSidebar.tsx
- app/components/Metadata.tsx
- app/models/dataset.ts
- app/scss/_metadata.scss
- app/scss/style.scss
- package.json
- yarn.lock
- Pulled in a refactored the metadata component from Qri Frontend.  
- Added some custom display logic for different fields
- If no custom logic applies, uses `JSON.stringify(value)`
Closes #58
> 58 meta layout

- app/components/Body.tsx
- app/components/CommitDetails.tsx
- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/DatasetComponent.tsx
- app/scss/_dataset.scss
Adds a 30px tall header to all component views, indicating the name and status of what is currently being viewed in the main content area (Closes #38)
^^ includes refactoring some of the parts of `FileRow` so they can be used in multiple places (the status dot generator, and the component displayName lookup)
All "Dataset Component" Components (ugh) are now wrapped in `DatasetComponent`, removing redundant switches in `Dataset` and `CommitDetails` to determine what to show in the main content area.
Adds a few general CSS improvements, including consistent separators for content panes.  Closes #81 (CSS overlap bug)
> feat: add component content header with status

- app/components/CommitDetails.tsx
- app/components/DatasetSidebar.tsx
Removes @b5 avatar images.  The containing divs are commented out so we can add them back once we have proper identity management w/ Qri cloud.
> refactor: remove hard-coded avatar image

- app/actions/api.ts
- app/actions/workingDataset.ts
- app/components/Dataset.tsx
- app/containers/DatasetContainer.tsx
- app/models/store.ts
- app/reducers/workingDataset.ts
- Updates the store to include `mtime` for each component
- When `Dataset` `didUpdate`, compare previous `mtime` with new `mtime`, determine which components need updating (body or everthing else)
- New actions to `resetBody()` and `resetOtherComponents`
Closes #113
> feat: update components on mtime diff

- app/components/Dataset.tsx
- app/utils/registry.ts
closes #145
also change QRI_CLOUD_URL to `https://qri.cloud`.
> fix(cloud link): show in cloud should use QRI_CLOUD_URL

- .gitignore
- app/actions/session.ts
- app/components/App.tsx
- app/reducers/index.ts
- app/reducers/myDatasets.ts
Store the session info in Session
If the session is different, reset the selection and pull myDatasets
If we are pulling myDatasets from page 1, added logic that would make sure we are not holding onto the previous list of datasets
closes #152
> fix(signin/signup): get session info from response to signin/signup

- app/components/Dataset.tsx
- app/main.development.js
- Adds 'Reload' to the 'View' menu with shortcut Command-R, reloading the app. (Closes #138)
- Makes the discord tooltip multi-line, so it appears below the icon instead to the left
> feat: Command-R Shortcut

- app/main.development.js
When a user closes the window, the app is moved to the background.  When they bring the app back to the foreground, the window will be shown again.  (Closes #132)
> feat: show window on refocusing app

- CHANGELOG.md
- Makefile
- app/main.development.js
- app/package.json
- package.json
- version.js
updated changelog & versions
Welcome to the Qri Desktop release candidate! Qri Desktop is an app for creating and managing datasets and versions (meant to replace the Qri Frontend). It gives a UI to our qri commandline tool. This is a release candidate, so all features have not been perfected yet. Qri Desktop will make it easy for you to create and version datasets, look back through the history of your datasets to see what has changed, and to double check your changes before you commit them! You can also publish your datasets and add colleagues datasets' that have already been published. 
Qri is an amalgamation of three hefty areas: a version control system, a network to other data users, and a database for your local data. In order to make working with Qri and it's local database …
> chore(release candidate): version v0.1.0-rc1

- app/reducers/ui.ts
Adds a reducer for the `DATASET_SUCCESS` event that closes the dataset list.  (Dataset list should close automatically if user switches datasets or adds a new dataset.  Closes #135
> fix: close the dataset list when a new dataset is loaded

- app/actions/api.ts
- app/components/Dataset.tsx
- app/components/DatasetList.tsx
- app/components/form/TextInput.tsx
- app/components/modals/CreateDataset.tsx
- app/components/modals/Header.tsx
- app/scss/_dataset-list.scss
- app/scss/_dataset.scss
- app/scss/_dialog.scss
- app/scss/style.scss
Refactors the Create Dataset Modal, prompts the user for an input file, dataset name, and path to create a linked directory.
Gives user feedback about what will happen when they click 'Create Dataset'
Pre-populates the dataset name with the filename minus its extension
Styles the add dataset button in the dataset list, adds a create dataset button.  Each fires its respective Modal.
> New dataset modal

- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/DatasetComponent.tsx
- app/components/ParseError.tsx
- app/models/store.ts
Also adds a `ParseError` component that is shown in place of the component, letting the user know that there is an error and where to fix it.
closes #172
> fix(component status): add indication that there is a parsing error

- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/DatasetList.tsx
- app/components/DatasetSidebar.tsx
- app/components/ParseError.tsx
- app/containers/DatasetListContainer.tsx
- app/main.development.js
Added event listener to DatasetList
Refactors app menu to include link to discord & renames "Show Dataset List" to "Toggle Dataset List"
Adds back history tab even if dataset has no history. Tab is disabled and formatted differently.
`Open in finder` bug fixed
closes #173 
closes #176 
closes #170 
closes #171
> fix(*): various bugs from tutorial walkthrough

- app/actions/selections.ts
- app/components/Signin.tsx
- app/components/Signup.tsx
- app/components/form/DebouncedTextInput.tsx
- app/components/form/TextInput.tsx
- app/containers/RoutesContainer.tsx
- app/reducers/selections.ts
- app/routes.tsx
This should be refactored and thought through a bit more.
The first issue: we should be waiting for authorization before fetching a user's datasets.
This commit also adds pressing `enter` while in the password field to continue on signin (but only if we are in a state to submit)
closes #166 
closes #167
> fix(selection): when we signin/signup, clear the selection

- app/actions/api.ts
- app/components/App.tsx
- app/components/Dataset.tsx
- app/components/modals/CreateDataset.tsx
- app/reducers/selections.ts
- app/reducers/workingDataset.ts
- app/store/api.ts
Updates Create Dataset Modal to work with changes in [qri#913](https://github.com/qri-io/qri/pull/913) (Closes #141)
User provides input file, dataset name, path to create linked directory.  On submit, they arrive at the Dataset view looking at a new dataset
> feat: init dataset

- package.json
Adds the correct html file to `files` in `package.json`, fixing the 'Not allowed to load local resource' error we were seeing on the production build
> fix: add production html to package.json files

- app/components/CommitDetails.tsx
- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/form/TextInput.tsx
- app/components/modals/CreateDataset.tsx
- app/components/modals/Modal.tsx
- app/main.development.js
- app/reducers/selections.ts
- app/scss/_dataset.scss
- app/scss/_forms.scss
- app/scss/_welcome.scss
- app/utils/formValidation.ts
- test/app/utils/formValidation.test.ts
- test/runTests.js
- yarn.lock
- Remove header tooltips, show full `peername/name` in current dataset area (Closes #169)
- Fix unable to quit from MacOS dock (Closes #164)
- Fix activeTab localstorage <-> state mismatch (Closes #201)
- Add dataset name validation in `CreateDataset` modal (Closes #202)
- Remove unnecessary text from commit component list, fix width (Closes #52)
- Adds tooltips, new text, and style tweaks to Create Dataset Modal (Closes #190)
> Various fixes and refactoring

- app/components/ComponentList.tsx
- app/components/modals/CreateDataset.tsx
Handles windows file paths when displaying component filenames, and when parsing filename during create dataset.  (Closes #217 )
> fix: handle windows paths

- app/actions/api.ts
- app/actions/mappingFuncs.ts
- app/components/App.tsx
- app/components/DatasetList.tsx
- app/components/form/CheckboxInput.tsx
- app/components/modals/RemoveDataset.tsx
- app/containers/AppContainer.tsx
- app/models/modals.ts
- app/models/store.ts
- app/scss/_dataset.scss
- app/scss/_dialog.scss
- app/scss/_modal.scss
- app/scss/_site.scss
- app/scss/_welcome.scss
- Adds a contextual menu on dataset list items for 'Remove...' (Closes #118)
- Adds a remove dataset modal, asking the user whether they would like remove files (if the dataset is fsi linked)
- Refactors modal types, and the implementation of modals in App.tsx.  All are consolidated under a single CSS transition, and are mounted based on the type of Modal that is currently set in state.
> feat: dataset removal

- app/actions/api.ts
- app/components/App.tsx
- app/components/Dataset.tsx
- app/components/DatasetList.tsx
- app/components/chrome/HeaderColumnButtonDropdown.tsx
- app/components/modals/PublishDataset.tsx
- app/components/modals/UnpublishDataset.tsx
- app/containers/AppContainer.tsx
- app/main.development.js
- app/models/modals.ts
- app/scss/_dataset-list.scss
- app/scss/_dataset.scss
- app/scss/_dialog.scss
** Contains work from #226, merge that first **
Adds modals for dataset publish and unpublish. (Closes #192)
Refactors the layout and style of the dataset list
- Fixes a z-index issue where dropdowns in header were appearing behind the data table
- Adds an icon next to each dataset in the list, can be used in the future for status, etc
- Turns the add and new buttons into proper buttons, adding glyphs to each
> feat: publish and unpublish modals

- app/actions/api.ts
- app/actions/mappingFuncs.ts
- app/actions/selections.ts
- app/actions/workingDataset.ts
- app/components/App.tsx
- app/components/CommitDetails.tsx
- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/DatasetComponent.tsx
- app/components/DatasetList.tsx
- app/components/DatasetSidebar.tsx
- app/components/ParseError.tsx
- app/components/modals/RemoveDataset.tsx
- app/main.development.js
- app/models/modals.ts
- app/models/store.ts
- app/reducers/selections.ts
- app/reducers/workingDataset.ts
- app/store/api.ts
- test/app/reducers/selections.test.ts
Closes #228, a bug where we observed the create dataset flow resulting in an awkward state requiring a reload.
On investigation, the the error was due to API calls with `?fsi=undefined`.
This PR refactors how we store state for a dataset's linked status, as follows:
- We had 3 different names for linked status: `isLinked` (boolean), `linkpath` (string), and `fsiPath`(string).  These are now fully standardized as `fsiPath`, which is what the API returns (this simplifies mapping functions).  `isLinked` is used only in the `Dataset` component as a local convenience variable.
- `isLinked` and `published` are now removed from `selections`.  They should never have been there as they aren't user selections that need to be persisted, they are simply the state of the `workingDataset` (this also …
> refactor: standardize fsiPath, isLinked, linkpath, simplify selections

- app/components/Body.tsx
- app/containers/BodyContainer.tsx
- app/reducers/workingDataset.ts
- package.json
- yarn.lock
Eliminates the rendering that was occurring on each successful poll of `/status`.  
The reducer now performs a `deepCopy` and will return the original state unless something has changed in the API response.
This PR also moves logic for extracting column headers out of the Body container and into the Body component.
> refactor: eliminate unecessary polling render

- app/backend.js
closes #246.
When running the complied app, you should now be able to search your filesystem for `io.qri.desktop` and see a file called `qri.log`. It'll be in your tmp directory.
> feat(backend): log backend output to tmp/io.qri.desktop/qri.log

- app/actions/selections.ts
- app/components/App.tsx
- app/components/modals/CreateDataset.tsx
- app/containers/AppContainer.tsx
- app/models/store.ts
- app/reducers/selections.ts
Adds `datasetPath` to localStore, adds `setDatasetPath` action, adds `useEffect()` in `CreateDataset` modal to persist the datasetPath immediately after the user chooses a directory.
Closes #251
> feat: persist dataset path

- app/actions/api.ts
- app/actions/selections.ts
- app/actions/ui.ts
- app/components/App.tsx
- app/components/Body.tsx
- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/DatasetList.tsx
- app/components/modals/AddDataset.tsx
- app/components/modals/CreateDataset.tsx
- app/containers/AppContainer.tsx
- app/containers/MetadataEditorContainer.tsx
- app/containers/SaveFormContainer.tsx
- app/models/session.ts
- app/models/store.ts
- app/reducers/index.ts
- app/reducers/selections.ts
- app/reducers/ui.ts
- app/reducers/workingDataset.ts
- app/scss/_dataset.scss
- app/store/api.ts
- test/app/reducers/selections.test.ts
closes #274 
closes #279 
closes #272 
closes #277 
closes #281
closes #275 
closes #276 
also:
- final fix on fetching session, keep app in loading state until session returns
- simplify process on reseting components, fixes bugs with saving after meta editing
- we keep going back and forth on this, but I now don't think that dataset_success should write over the body
- refactor Dataset to remove `getDerivedPropsFromState` to `ComponentDidUpdate`
- refactored how we set commits in selection after we fetchHistory for the first time
> fix(*): Lots o fixes

- app/components/KeyValueTable.tsx
- app/components/Metadata.tsx
- app/components/Schema.tsx
- app/components/TwoDSchemaLayout.tsx
- app/components/form/MultiStructuredInput.tsx
- app/reducers/selections.ts
- app/scss/_schema.scss
- app/scss/_site.scss
Adds a simple tabular layout for csv `schema` components.  If the working dataset's `schema` looks like a qri's common csv format, it will render a table instead of the JSON viewer.
`title`,`type`, and `description` are first class keys, all others are displayed in a simple key-value table.
Closes #49
> feat: 2d schema layout

- app/actions/api.ts
- app/components/App.tsx
- app/components/KeyValueTable.tsx
- app/components/Metadata.tsx
- app/components/Schema.tsx
- app/components/TwoDSchemaLayout.tsx
- app/components/form/MultiStructuredInput.tsx
- app/components/modals/AddDataset.tsx
- app/reducers/selections.ts
- app/reducers/ui.ts
- app/scss/_schema.scss
- app/scss/_site.scss
- app/utils/formValidation.ts
- test/app/reducers/selections.test.ts
Add Dataset Modal Improvements:
- Adds a dataset path input (directory chooser)
- Adds dataset reference validation with error message (submit button disabled unless dataset path and dataset reference are both valid)
- Dataset path input populated from persisted state
TODO: 
- Update `addDataset` action to send `dir`, `mkdir`, as params
Depends on backend work to accept `dir` and `mkdir`
> feat: add modal improvements

- app/components/App.tsx
- app/components/AppLoading.tsx
- app/components/DatasetSidebar.tsx
- app/main.development.js
- app/package.json
- package.json
- test/e2e/e2e.spec.ts
- version.js
- yarn.lock
#288 
#271 
& brings e2e tests in line with refactored router/removal of the `no datasets` page
> fix(history tab, e2e-tests, bootstrapping): various fixes

- app/components/App.tsx
- app/components/BodyTable.tsx
- app/components/modals/CreateDataset.tsx
- app/containers/AppContainer.tsx
- app/reducers/ui.ts
- app/scss/_drag-drop.scss
- app/scss/_welcome.scss
- app/scss/style.scss
Drag and drop a csv or json file over the app to create a new dataset.
Long term, dragging and dropping over the app will automatically initialize and save a version of the dataset, choose a name, and save it in a default directory. The finer points of these are still being debated. For now, drag and drop the file in and the user is sent to a modal that is filled out with defaults, giving the users an opportunity to intercept our assumptions. Clicking create initializes a dataset and sends the user to the body of that dataset.
> feat(drag-and-drop): drag and drop a data file to create a dataset

- app/actions/api.ts
- app/actions/ui.ts
- app/components/Body.tsx
- app/components/BodyTable.tsx
- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/DetailsBar.tsx
- app/containers/BodyContainer.tsx
- app/containers/DatasetContainer.tsx
- app/containers/DetailsBarContainer.tsx
- app/models/details.ts
- app/models/store.ts
- app/reducers/commitDetail.ts
- app/reducers/ui.ts
- app/reducers/workingDataset.ts
- app/scss/_dataset.scss
- app/scss/_transitions.scss
First pass:
1) add Details type (with options NoDetails and StatsDetails)
2) add DetailsBar component and container
3) add `setDetailsBar` action that adds the details to the UI state
4) add `DetailsBarContainer` to `Dataset` component
5) add `fetchStats` and `fetchCommitStats` to get the stats from the backend, and store them in the `workingDataset` and `commitDetails` reducers
depends on qri-io/qri#1020
> feat(detailsBar): let's add a details bar on the dataset body page

- app/components/Body.tsx
- app/components/BodyTable.tsx
- app/components/DetailsBar.tsx
- app/scss/_body.scss
Adds column highlighting in body tables:
- subtle highlight on hover
- cursor:pointer on hover
- darker highlight when selected (details pane visible)
- remove highlight when details pane is closed
Minor css tweaks: removes border-bottom on header row, and border-left on first data column
> feat: style selected column header when stats are displayed

- app/components/Code.tsx
- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/DatasetComponent.tsx
- app/components/Transform.tsx
- app/containers/TransformContainer.tsx
- app/models/store.ts
- app/reducers/workingDataset.ts
- stories/1-CodeViewer.stories.tsx
this adds _very_ basic support for displaying transforms within desktop. Meant mainly as a thing we can iterate on. I've also added a story around the `Code` component, hoping we can make that look not terrible.
> feat(transform): initial support for transform display

- DEVELOPER.md
- RELEASE_PROCESS.md
because notarization has mucked up the building and signing of the app, I am adding more detailed notes about how to get a functioning version of Qri Desktop zip file on our releases page. This is important for autoupdate.
> docs(release): adds steps on how to put out a release

- app/actions/api.ts
- app/components/Dataset.tsx
- app/components/DatasetReference.tsx
- app/components/DatasetSidebar.tsx
- app/containers/DatasetSidebarContainer.tsx
- app/reducers/selections.ts
- app/reducers/workingDataset.ts
- app/scss/_dataset.scss
Adds "edit-in-place" UI for renaming datasets when in the dataset view.
Provides visual feedback when the proposed name is invalid, provides success or error toasts after backend response.
Editing happens in a new component `<DatasetReference>`, which could theoretically be re-used to rename datasets in the Collection view.
> feat: add dataset rename

- app/actions/api.ts
- app/components/App.tsx
- app/components/ComponentList.tsx
- app/components/Dataset.tsx
- app/components/DatasetReference.tsx
- app/components/DatasetSidebar.tsx
- app/components/UnlinkedDataset.tsx
- app/components/modals/LinkDataset.tsx
- app/reducers/selections.ts
- app/scss/_buttons.scss
- app/scss/_chrome.scss
- app/scss/_dataset.scss
- app/scss/_sidebar-layout.scss
Need to merge @chriswhong 's `streamline-import` branch first
closes #342 
closes #355 
closes #351 
Also: show `NoDataset` page, only if there is no dataset selected
Rather then waiting to see if any datasets are loaded, show the NoDatasets component in the Dataset page if there is no dataset selected.
This is an interim step, eventually we won't show the dataset page when there is no dataset selected.
> refactor: Minor ui fixes

- app/actions/api.ts
- app/components/App.tsx
- app/components/CommitDetails.tsx
- app/components/Dataset.tsx
- app/components/Navbar.tsx
- app/components/chrome/HeaderColumnButtonDropdown.tsx
- app/containers/AppContainer.tsx
- app/reducers/workingDataset.ts
Closes #363 
Refactors flow of data loading API calls to prevent unnecessary calls when navigating around the app.  
- Listener for workingDataset fetch is moved up to `App` level
- Ensured that renaming a dataset would not cause a fetch (it used to because the name and peername had changed)
- Switching between status and history tabs no longer causes any fetching
- Switching between Collection and Dataset view no longer causes any fetching
> refactor: clean up state loading flow

- app/components/Dataset.tsx
- app/components/ReadMe.tsx
- app/reducers/commitDetail.ts
- app/scss/_dataset.scss
- yarn.lock
For now, since it's pretty unlikely that someone will be editing the readme on the app and in their own editor at the same time, let's refactor the readme so that the line-jump error is fixed.
This refactor waits until we are focused on the window before checking if the given value is diffferent then the value we are displaying on the page. If it is, then we replace the display value with the given value. It's not perfect and there are some rendering issues, but this is a good stop-gap.
This also fixes the DetailsBar formatting issues
closes #345 
closes #366
> refactor(readme): imperfect solution to line jump

- app/actions/api.ts
- app/components/App.tsx
- app/components/Dataset.tsx
- app/components/DatasetList.tsx
- app/components/DatasetReference.tsx
- app/components/NoDatasets.tsx
- app/components/UnlinkedDataset.tsx
- app/components/modals/AddDataset.tsx
- app/components/modals/CreateDataset.tsx
- app/components/modals/Header.tsx
- app/components/modals/LinkDataset.tsx
- app/containers/AppContainer.tsx
- app/containers/DatasetContainer.tsx
- app/package.json
- app/reducers/commitDetail.ts
- app/reducers/selections.ts
- app/reducers/workingDataset.ts
- app/scss/_dataset.scss
- app/scss/_dialog.scss
- app/utils/formValidation.ts
- package.json
- test/app/reducers/selections.test.ts
- test/app/utils/formValidation.test.ts
- version.js
The `ipcRenderer.on()` functions that we use to hook into the electron menu are event listeners. We haven't been handling the removal of these listeners in the `App` and `Dataset` components. For each listener we add in `componentDidMount` we need to remove it in `componentDidUnmount`.
This commit also fixes some styling on the Dataset component when a dataset is not `checkedout`, it clears the selection once you've successfully removed a dataset, and also adjusts the no dataset selected state to include navigation that will send you back to the collections page.
closes #368 - remove auto checkout from Create and Add modals/flow, also remove ability to checkout a dataset that is not in your namespace, until we come up with an explicit plan (remove ability for Desktop users to foot gun …
> fix(App, Dataset, Remove): fix eventListener leak and clearing selection after a remove

- CHANGELOG.md
- app/package.json
- package.json
- version.js
No features, so kept the changelog notes short:
"We've got a patch release! This patch release cleans up some bugs around fetching, event listeners, dataset naming, and general app flow!"
Along with the list of bugs
> chore(version): version bump to `0.3.1`

- app/backend.js
- app/components/App.tsx
- app/main.development.js
When launching the qri backend, always log its output to a temporary file. If a developer wants to see output in a terminal, they can either run `qri connect` themselves, or they can `tail -f` the log. The log filename uses the current day in the filename.
In development mode, try to locate an installed `qri` binary, which makes it easier to develop both desktop and the backend at the same time.
Add a menu item under 'Help' which lets the user copy the debug log to a path.
Output a few useful pieces of info: which version of the qri backend was launched, the path to the the backend, the path to the log file.
> feat(logging): Log to a file, menu item to export it

- app/components/chrome/Icon.tsx
- app/scss/4.0/icons.scss
- app/scss/style.scss
- stories/2-Icons.stories.tsx
The `Icon` component should encompess all the necessary icons for the app.
We are wrapping the FontAwesomeIcon component. However, some icons we need are not part of the free set of FontAwesomeIcons, so, for now, those icons contains the `faQuestionCircle` icon, and will be replaced with svgs asap.
The icons that do not have equivalents, or otherwise need replacing, are: 
- boolean
- object
- array
- integer
- number
- string
- null
- commit
> feat(icon): `Icon` component

- app/components/DatasetList.tsx
- app/components/DatasetReference.tsx
- app/components/Metadata.tsx
- app/components/modals/LinkDataset.tsx
- test/e2e/e2e.spec.ts
We now have flows for:
- open window
- accept terms of service by clicking accept and get taken to signup
- create a new account, taken to datasets page
- signout and sign in
- create new CSV dataset from a data source
- checkout a dataset
- write the body to the filesystem & commit
- create a meta & commit
- rename a dataset
Checkout fails, and each subsequent test relies on having a checked-out dataset, so each subsequent  test fails
> test(e2e): round out e2e with more flows, regardless of if they pass

- RELEASE_PROCESS.md
- app/actions/api.ts
- app/actions/mutations.ts
- app/actions/selections.ts
- app/components/Body.tsx
- app/components/Commit.tsx
- app/components/DatasetList.tsx
- app/components/MetadataEditor.tsx
- app/components/modals/LinkDataset.tsx
- app/containers/BodyContainer.tsx
- app/containers/CommitContainer.tsx
- app/containers/CommitDetailsContainer.tsx
- app/reducers/mutations.ts
- app/reducers/selections.ts
- app/reducers/ui.ts
- app/reducers/workingDataset.ts
- test/e2e/e2e.spec.ts
- test/utils/e2eTestUtils.ts
Adjust the `saveWorkingDatasetAndFetch` and `Commit` components, along with the `mutations` reducer and actions to fix the flow after you commit.
We need to wait for both the commit to be successful and for the history list to update, inorder to show the user a clean commit experience. To do that, we've added a `saveComplete`/`SAVE_COMPLETE` action to the `mutations` reducer that gets called when save & history fetching is complete
Also adjusts the MetadataEditor to fix a content jumping problem
Also, also fixes a bug when navigating to a dataset using the dataset list.
After this pr, e2e tests are passing locally, but not on ci
> fix(commit, MetadataEditor): fix meta editing and the flow after you commit

- app/backend.js
- app/main.development.js
- package.json
- yarn.lock
using the electron-log package, which is lovely. From the [package documentation](https://www.npmjs.com/package/electron-log), this'll create a log file called `main.js` in a platform-dependent location:
* on Linux: `~/.config/{app name}/logs/{process type}.log`
* on macOS: `~/Library/Logs/{app name}/{process type}.log`
* on Windows: `%USERPROFILE%\AppData\Roaming\{app name}\logs\{process type}.log`
> feat(main process logging): add logging for main process

- CHANGELOG.md
- app/package.json
- package.json
- version.js
- webpack.config.development.js
- webpack.config.production.js
- yarn.lock
This patch release fixes two visual bugs (packaged fonts and adjustments to the menus), restores the 'unpublish' option to the dataset page, and adds a number of reusable components that we will begin to surface as we release new features.
> chore(release): version bump to 0.3.4

- CHANGELOG.md
- app/package.json
- package.json
- version.js
- yarn.lock
upgrades electron and electron-builder, restoring auto-updating feature
> chore(release): version bump to 0.3.5

- app/actions/mappingFuncs.ts
- app/components/App.tsx
- app/components/dataset/DatasetDetailsSubtext.tsx
- app/components/item/DatasetItem.tsx
- app/components/item/VersionInfoItem.tsx
- app/components/modals/SearchModal.tsx
- app/components/network/Network.tsx
- app/components/network/NetworkHome.tsx
- app/models/store.ts
- stories/8-Item.stories.tsx
clicking on search results will take you to the network page, if the dataset is on the network, or the workbench if the dataset is local.
This also alters `DatasetItem` to take `VersionInfos` and adds the `datasetToVersionInfo` function which we won't need once the backend list (search, feed, list) responses are refactored to return arrays of VersionInfos.
> refactor(Search & Network): link the search results to routes

- app/actions/api.ts
- app/actions/session.ts
- app/components/workbench/Workbench.tsx
- app/constants.js
- app/store/configureStore.development.ts
- app/store/configureStore.production.ts
- app/store/wsMiddleware.ts
- test/e2e/e2e.spec.ts
- test/utils/e2eTestUtils.ts
depends on qri-io/qri#1125
This removes polling and adds websockets (as their own middleware). Currently, all code defining websockets & their actions all exist in the `wsMiddleware.ts` file. As websockets feature more heavily in the app, I imagine this will get refactored. 
closes #455 
closes #383
> feat(websockets): remove polling and add middleware for websockets

- app/components/network/NetworkHome.tsx
- app/scss/0.4.0/item.scss
- app/scss/_navbar.scss
- Adds some margin around list items in Network pane
- Treats `themeList` as a string (quick fix, it supposed to be an array, opened #462 about this)
- Increases the navbar width to 68px so the macOS window buttons appear centered
> Network pane fixes

- app/components/ErrorHandler.tsx
- app/constants.js
- app/index.tsx
- app/scss/0.4.0/errorHandler.scss
- app/scss/style.scss
We've been getting complaints from users of a "blank white screen", which is caused by unhandled exceptions in react code. This PR adds an `ErrorHandler` at the root of our tree with the `componentDidCatch` lifecycle event. It'll render this whenever react throws an unhandled error:
When an error is caught we manually clear local storage. Clicking reload will navigate the user back to a blank hash router, hopefully getting them out of whatever state caused the problem in the first place.
While we're learning from past lessons, we've continually gotten incredible ROI for time spent building tools that log and report errors. To that end, I've added a crash reporter to our error handler. Ideally this'll help us diagnose and address fixes faster without forcing users to send us data.
I'd love …
> feat(ErrorHandler): handle react errors, crash reports

- CHANGELOG.md
- app/package.json
- package.json
- version.js
Release notes 0.4.0
Welcome to the Qri Desktop App version 0.4.0!
This version is one of our biggest to date. We've got a whole slew of new features for you to explore & a number of bugs have been squashed. With this release you can now browse, search, and clone datasets, all within the app. We’ve brought dataset editing in-app, and we’re premiering our first visual diffing tool with the compare section.
The first big feature we’re showing off is our new Network page. Browse the Qri network in app! Preview featured and recently published datasets without having to download the full dataset. Find a dataset you want to view in its entirety? **Clone** the dataset! That will download it from the network to your computer.
This also means that when you publish, other users will be able to see …
> chore(release): version 0.4.0

- test/e2e/e2e.spec.ts
Simple check against `/health` for a local Qri node. On true throws an error which kills further tests. 
Related bug:
https://github.com/qri-io/desktop/issues/457
> test(e2e): ensure qri is not running when running tests

- app/actions/workbench.ts
- app/components/workbench/Workbench.tsx
- app/selections.ts
- app/selections/workbench.ts
added array of selections that we will need for the coming container refactor
added `writeDataset` function that combines `fsiWrite`, `setMutationsDataset`, and `setMutationsStatus`, adapted from the `handleSetDataset` function in `Workbench`
This pr just adds the functions, it doesn't remove any current functionality from the `Workbench` component
> feat(selections): adding workbench selections and actions

- CHANGELOG.md
- app/package.json
- package.json
- version.js
- yarn.lock
This release is all about minor bug fixes, clean up, stabilization, and updating the desktop app to work with the latest qri release!
Be sure to check out the latest [qri backend release](https://github.com/qri-io/qri/releases/tag/v0.9.7) to see the lovely fixes we inherit.
In a combined effort from the backend and desktop, we've fixed the export bug! Right-clicking the version you want to export, and clicking 'export this version', opens the save dialog, prefilled with a default zipname.
This desktop update adjusts our requests to meet the expectations of the latest qri backend's API
Because of those wonderful backend api changes, we were able to fix a long-standing bug where re-loading on the `workbench` page broke the app. Now you can reload to your heart's content
Combining websockets …
> chore(version): version bump to 0.4.1

- CHANGELOG.md
- app/package.json
- package.json
- version.js
Changelog/release message:
The Qri Desktop 0.4.2 patch fixes an export bug! It also fixes two minor bugs surrounding fetching datasets for display in the Workbench.
Be sure to check out the latest [qri backend release](https://github.com/qri-io/qri/releases/tag/v0.9.8) to see the other fixes we inherit.
> chore(release): version 0.4.2

- app/components/CrashReportSender.tsx
- app/components/ErrorHandler.tsx
- app/components/IncompatibleBackend.tsx
- app/components/MigratingBackend.tsx
- app/components/MigrationFailed.tsx
- app/components/ReportCrashAndReload.tsx
- stories/AppLaunch.stories.tsx
- stories/Error.stories.tsx
closes #567 
Builds the following new components for use in Desktop's handling of the backend qri migration:
1. `IncompatibleBackend`
2. `MigratingBackend`
3. `MigrationFailed`
Also builds new `ReportCrashAndReload` component to modulate functionality which can be shared by existing `ErrorHandler` component and new `MigrationFailed` one
> Migration components

- app/actions/ui.ts
- app/backend.js
- app/components/App.tsx
- app/main.development.js
- app/models/store.ts
- app/reducers/ui.ts
- app/selections.ts
closes #566 
My journey through this process has been decently well chronicled in the above issue!
My last comment would be, very open to re-structuring `BackendProcess` to take a `window` so that the main function is less unwieldy and is less responsible for coordinating the behavior. However, it might be nice to keep all the emitted events in the `main.development.js` file, so that behavior isn't hidden down in another class. Anyone have strong opinions?
Edit:
Backend is getting a refactor! Now commands won't "auto-trigger" a migration, unless you have the `--migrations` flag. And a command will fail w/ an exit error (`2`) if the config needs a migration. We can use these to remove the desktop's reliance on knowing about the QRI_PATH and keeping track of config revisions!
> feat(migration): adjust `BackendProcess`, `main.dev.js` & `App.ts` so we can coordinate migrations!

- app/components/ExternalLink.tsx
- app/components/Header.tsx
- app/components/chrome/Icon.tsx
- app/components/collection-v2/DatasetStatus.tsx
- app/components/platformSpecific/DatasetStatus.electron.tsx
- app/components/platformSpecific/DatasetStatus.web.tsx
- app/components/platformSpecific/ExternalLink.web.tsx
- app/scss/_dataset-status.scss
- app/scss/_header.scss
- app/scss/style.scss
- stories/Collection.stories.tsx
- stories/Header.stories.tsx
This PR checks off the first 2 components I enumerated in #576, which builds off designs from #554 
- A new `Header` component to eventually be used across the app but built just for Collection View for now
- A new `DatasetStatus` component to be utilized in the new Collection table view
> feat(Header & DatasetStatus): add new Header and DatasetStatus components

- .circleci/config.yml
- app/actions/api.ts
- app/backend.js
- app/components/App.tsx
- app/components/collection/CollectionHome.tsx
- app/components/modals/Modals.tsx
- app/components/modals/PullDataset.tsx
- app/components/network/LogList.tsx
- app/components/network/Network.tsx
- app/components/workbench/NoDatasetsMainContent.tsx
- app/main.development.js
- app/models/modals.ts
- app/models/store.ts
- app/selections.ts
- app/store/wsMiddleware.ts
- test/e2e/e2e.spec.ts
- test/utils/testQriBackend.ts
Now that we can successfully migrate, let's make sure that all the other functionality that needs updating is fixed!
closes #560
closes #555 
closes #556 
make sure e2e tests are running
relies on qri-io/temp_registry_server#4
> refactor(*): changes to get desktop to work with qri v0.9.9/v0.9.10 changes

- app/actions/api.ts
- app/package.json
- test/e2e/e2e.spec.ts
- version.js
We have removed the root endpoint in the backend, so all get requests must go through the `/get` endpoint
> refactor(api): adjust `fetchDataset` to use the `/get/` endpoint

- app/scss/0.4.0/network.scss
- app/scss/_dataset.scss
- package.json
- yarn.lock
Long sidebar content in the dataset view was preventing the user from clicking the status and history tabs. Closes #551
> fix: long dataset history overlaps status button

- app/components/Layout.tsx
- app/components/modals/RemoveDataset.tsx
Closes #534 
Here's a preview of what the modal now looks like when a user attempts to delete a dataset under their own username
> feat(Remove dataset): add warning for when a user removes own dataset

- app/components/modals/LinkDataset.tsx
- test/e2e/e2e.spec.ts
Closes #205 
Update copy from "Save Path" to "Checkout Location" and include help text to clarify what the fields in the checkout modal refer to
> Update "Save Path" Checkout modal copy 

- app/components/form/TextAreaInput.tsx
- app/components/form/TextInput.tsx
According to: https://stackoverflow.com/questions/28922275/in-reactjs-why-does-setstate-behave-differently-when-called-synchronously/28922465#28922465, using `onChange` along with `value` on input elements leads to problems when the element is changed asynchronously. Using `defaultValue` instead fixes this problem.
Fixes https://github.com/qri-io/desktop/issues/496.
> fix(commit): Don't push cursor to end of text input elements

- app/actions/api.ts
- app/actions/workbench.ts
- app/components/collection/Collection.tsx
- app/components/collection/UncommitedChangesPrompt.tsx
- app/components/collection/UncommittedChangesPrompt.tsx
- app/components/collection/WorkingComponentList.tsx
- app/components/collection/collectionHome/CollectionHome.tsx
- app/components/collection/layouts/DatasetLayout.tsx
- app/components/collection/layouts/DatasetMainContent.tsx
- app/components/item/VersionInfoItem.tsx
- app/components/modals/Modal.tsx
- app/models/qriRef.ts
- app/models/store.ts
- app/reducers/dataset.ts
- app/reducers/workbenchRoutes.ts
- app/reducers/workingDataset.ts
- app/selections.ts
closes #617 
closes #613 
A bunch of this cleans up functionality that was changed when we refactored the routes and refactored away from the "status" and "history" tabs.
- add notes on how to integrate new modals
- fixed bug in `workbenchRoutes` that was causing the history ref to reset when there was a new edit ref, and the edit ref to reset when there was a new history ref
- fixed bug that was causing double fetching b/c we weren't storing `peername` and `name` in the state tree when we fetched any dataset information
- refactored the "you have uncommitted changes" code into one component for easier future fixes & refactored to ensure it was working as expected
- restored the ability to `Discard changes` in linked and unlinked datasets.
> fix(*): clean up `discardChanges`, double-fetching bugs, and the "uncommited changes" prompt

- app/components/collection/WorkingComponentList.tsx
- app/components/collection/datasetComponents/Readme.tsx
- app/components/collection/datasetComponents/ReadmeEditor.tsx
- app/scss/0.4.0/dataset.scss
- app/scss/_dataset.scss
Adds click listeners to hijack clicks on rendered readmes (both in historic commit readme display and when previewing a working readme), so that links are intercepted and sent to electron's external link opener.
Includes some css cleanup to fix a double vertical scrollbar on the readme editor and a non-scrolling structure viewer.  All components should overflow/scroll in the same way now.
Removes `color='light'` prop on WorkingComponentList items so each component's icon is shown (they were white on white and not visible)
closes #540
> fix: external readme links

- app/components/collection/LogList.tsx
- app/components/collection/collectionHome/CollectionHome.tsx
- app/components/collection/layouts/DatasetSidebar.tsx
- app/components/item/VersionInfoItem.tsx
- app/components/item/WorkingLogListItem.tsx
- app/components/modals/CreateDataset.tsx
- app/components/modals/Modals.tsx
- app/components/network/NetworkSidebar.tsx
- app/models/modals.ts
- app/scss/_dataset.scss
- test/e2e/e2e.spec.ts
- test/e2e/e2e_test_flows.md
- test/utils/e2eTestUtils.ts
**There are two tests that are still failing, both in the same way.** When we go to switch between commits & check that the commit titles are correct (this is how we determine that the versions have actually been changed, since we don't have the path information and therefore can't use the path to verify we have navigated to the correct commit). For some reason, even though the div definitely exists, we cannot find the `#history-commit` on the page. Would love it if someone could take a look.
However, this is in a good enough place that even if someone isn't able to de-bug, I'm comfortable merging, since, for most cases, folks can use this to make sure they aren't breaking expected app behavior. 
Three notes:
1) DatasetReference was added back in because otherwise there is no way to …
> test(e2e): get e2e tests to pass with refactorings

- app/actions/api.ts
- app/components/collection/collectionHome/DatasetList.tsx
- app/models/qriRef.ts
- app/models/store.ts
add our first bulk action. A few things left for cleanup here:
* buttons should dim while bulk action is executing. they're disabled during the whole time
* the toast that shows 'pulling X datasets' should  stay up, and not have a warning
* currently error responses from the backend are still reporting success?
> feat(collection home): support bulk pulling

- app/components/BodyTable.tsx
Previously, we were only fetching the next page if the scrollHeight was
exactly equal to the scrollTop + the offsetHeight. It looks like this
calculation was thrown off by style changes and the scroll-x bar. We now
include a 'buffer' into the calculation. If the scrollHeight is within
10px of the scrollTop + offsetHeight, we attempt to fetch (barring that
we have already `fetchedAll`)
closes #639
> fix(body): relax stipulations for fetching next page

- app/actions/platformSpecific/export.electron.ts
- app/actions/platformSpecific/export.web.ts
- app/components/CommitDetails.tsx
- app/components/collection/DatasetHeader.tsx
- app/components/collection/LogList.tsx
- app/components/collection/collectionHome/TableRowHamburger.tsx
- app/components/collection/layouts/DatasetLayout.tsx
- app/components/form/ComponentAndFormatPicker.tsx
- app/components/modals/ExportDataset.tsx
- app/components/modals/RemoveDataset.tsx
- app/main.development.js
- app/models/modals.ts
- app/scss/0.4.0/dataset.scss
- app/scss/_form.scss
- app/scss/_modal.scss
- stories/Network.stories.tsx
- test/e2e/e2e.spec.ts
- test/e2e/e2e_test_flows.md
we don't have support for per-component export in the backend at the moment, so I've moved the dataset component picking stuff into it's own react component for future use in an "advanced" export section.
I'd also like the option to export the entire dataset as a JSON file. I use that format a bunch, it'd be great to have at some point in the future.
> feat(export): wire up export modal with csv & zip options

- app/components/collection/collectionHome/StatusIcons.tsx
- app/components/collection/collectionHome/TableRowHamburger.tsx
- app/components/network/NetworkHome.tsx
- webpack.config.development.js
* fix: remove "home" header from network home
* fix: clicking an unpublished status icon in collection home no longer opens a link
* fix: disable SQL / compare view in production AND dev environments
> feat(CollectionHome): add "pull" to row hamburger menu

- test/utils/e2eTestUtils.ts
this is causing too many false negatives. Adding a `waitUntil` for the
specified elements to exist before checing that the username is correct
> test(e2e): adjust `atDataset`

- app/backend.js
- app/components/App.tsx
- app/components/PortOccupied.tsx
- app/components/collection/collectionHome/DatasetsTable.tsx
- app/components/collection/datasetComponents/Readme.tsx
- app/components/collection/datasetComponents/ReadmeEditor.tsx
- app/components/modals/ExportSubmitButton.tsx
- app/constants.js
- app/main.development.js
- app/models/store.ts
- app/platformSpecific/backendUrl.electron.js
- app/platformSpecific/backendUrl.web.js
- app/scss/_welcome.scss
- package.json
- yarn.lock
new dependancy `fkill`: https://www.npmjs.com/package/fkill
In this commit, we refactor our `checkNoActiveBackendProcess` to also kill any processes at port `2503` if we aren't able to figure out the version number or if the version number it returns is not the expected version.
> fix(backend): kill any `qri connect` processes that aren't compatible

- app/components/Layout.tsx
- app/components/changes/DatasetSummaryDiff.tsx
- app/components/changes/StatDiff.tsx
- app/components/changes/StringDiff.tsx
- app/components/chrome/Segment.tsx
- app/components/chrome/StatusDot.tsx
- app/components/collection/DatasetChanges.tsx
- app/components/collection/datasetComponents/Body.tsx
- app/components/item/LabeledStats.tsx
- app/components/item/StatDiffRow.tsx
- app/components/modals/platformSpecific/ExportSubmitButton.electron.tsx
- app/components/modals/platformSpecific/ExportSubmitButton.web.tsx
- app/components/nav/NavTopbar.tsx
- app/reducers/dataset.ts
- app/reducers/log.ts
- app/reducers/selections.ts
- app/reducers/workingDataset.ts
- app/utils/fileSize.ts
- stories/12-ChangeReport.stories.tsx
- stories/data/change_report_sample_api_response.json
- test/app/reducers/selections.test.ts
- test/e2e/e2e.spec.ts
- test/utils/e2eTestUtils.ts
- StatusDot - when 'unmodified' we now have an option to show text that indicates that there are "No Changes"
- Segment - optional `startOpen` param that defaults to `true`. When `false`, the `Segment` starts closed
- StringDiff - when a component is "unmodified", default to having all text displayed
- ChangeReport - “Base” is red “Compare” is green
- StringDiff - Structure should by default start "rolled up" aka `startOpen` === false
- Labeled stats - Now we expect `Stat` to have another field `inBytes`. When a `Stat` has a `number` value & `inBytes` is true, we display the stat in Gb, Mb, b, etc.
- SummaryItem - when we iterate through the given Stats, if one of the stats is "totalSize", send over "File Size" as the label, and ensure `inBytes` is `true`.
- DatasetChanges - adjust layout …
> fix(`Changes`): first round styling adjustments based on feedback
